vich_uploader:
    db_driver: orm

    mappings:
        project_images:
            uri_prefix:         /project/image
            upload_destination: '%kernel.project_dir%/public/project/image'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true