easy_admin:
  entities:
    Companie:
      class: App\Entity\Companies
      disabled_actions: ['edit','new']
      label: 'Entreprise'
      list:
        title: 'Entrepririse'
        fields:
        - { property: 'CompanieName', label: 'Nom' }
        - { property: 'FullAdress', label: 'Adresse' }
        - { property: 'phoneNumber', label: 'Téléphone' }
        - { property: 'employees.count', label: 'Effectif' }
        - { property: 'project.count', label: 'Nombre de projets' }
