easy_admin:
  entities:
    User:
      class: App\Entity\User
      label: 'Utilisateurs'
      list:
        title: 'Utilisateurs'
        fields:
          - { property: 'lastName', label: 'Nom' }
          - { property: 'firstName', label: 'Prénom' }
          - { property: 'phoneNumber', label: 'Téléphone' }
          - 'email'
          - { property: 'isAllowed', label: 'Authorisé' }
          - { property: 'Projects.count', label: 'Projets ajouté' }
          - { property: 'Companies_added.count', label: 'Entreprises ajouté' }
          - { property: 'employees_added.count', label: 'Contacts ajouté' }
      new:
        title: 'Ajouter un Utilisateur'
        fields: &User
          - { property: 'last_name', type: 'text', label: 'Nom'}
          - { property: 'first_name', type: 'text', label: 'Prénom'}
          - { property: 'phone_number', type: 'text', label: 'Numéro de téléphone'}
          - { property: 'email', type: 'email', label: 'Email'}
          - { property: 'roles', template: 'admin/Backend/userRolesForm.html.twig', label: 'Permitions', type_options: { block_name: 'roles', mapped: false }}
      edit:
        title: 'Modifier un Utilisateur'
        fields: *User
